[settings]
auto_update = true
auto_update_check_duration = "3d"
idiomatic_version_file_enable_tools = ["node", "java"]
java.shorthand_vendor = "temurin"
minimum_release_age = "3d"

lockfile = true
activate_aggressive = true
minimum_release_age_excludes = ["claude", "codex", "pi", "gemini"]

[tools]
node = "22"
go = "1.26"
java = "21"
python = "3.12"

uv = "latest"

codex = "latest"
pi = "latest"
claude = "latest"
gemini = { version = "latest", allow_builds = ["@github/keytar", "node-pty"] }

cosign = "3"
crane = "0.22"
fzf = "latest"
gitleaks = "8"
restic = "0.18"
direnv = "latest"
yq = "4"
k9s = "latest"
biome = "latest"

[dotfiles]
"~/.config/mise/config.toml" = { mode = "track" }
